obstacle_range: 3.0
raytrace_range: 3.5

#Robot size: 0.70 x 0.60
# footprint: [[-0.380, -0.320], [-0.380, 0.320], [0.380, 0.320], [0.380, -0.320]]
robot_radius: 0.500

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: laserscan kinect_front kinect_back
laserscan: {sensor_frame: lidar_frame, data_type: LaserScan, topic: laserscan, marking: true, clearing: true}
kinect_front: {sensor_frame: kinect_front_link, data_type: PointCloud2, topic: kinect_front/depth/points, marking: true, clearing: true}
kinect_back: {sensor_frame: kinect_back_link, data_type: PointCloud2, topic: kinect_back/depth/points, marking: true, clearing: true}